name: Get card abbreviations

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"


jobs:
  get_abbreviations:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: "${{ github.repository }}.wiki"
          path: .wiki

      - name: Generate abbs json
        run: |
          WIKI_PATH=.wiki/Home.md
          ABBS_JSON=compass/data/abbs.json
          json="{ "
          while read line; do
              if [[ $line =~ ^\|\ ([0-9]{6,})\ \|\ [NRSU]{1,2}\ \|\ .\ \|\ .+\ \|\ (.*)\ \|$ ]]; then
                  json="$json\"${BASH_REMATCH[1]}\":[\"${BASH_REMATCH[2]//, /\",\"}\"],"
              fi
          done < $WIKI_PATH
          json=${json/%?/}}
          echo $json | jq "." > $ABBS_JSON

      - name: Remove unneeded files
        run: |
          rm -rf .wiki

      - name: Push to master
        run: |
          git add compass/data/abbs.json
          if ! git diff --exit-code --quiet
          then
            git config user.name github-actions[bot]
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git add compass/data/abbs.json
            git commit -m "[actions] Update abbreviations json"
            git push
          fi
