name: Get card abbreviations

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"


jobs:
  get_abbreviations:
    runs-on: ubuntu-latest

    env:
      COMMIT_MESSAGE: commit-message.txt

    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: "${{ github.repository }}.wiki"
          path: .wiki

      - name: Generate abbs json
        run: |
          WIKI_PATH=.wiki/Home.md
          ABBS_JSON=compass/data/abbs.json
          json="{ "
          while read line; do
              if [[ $line =~ ^\|\ ([0-9]{6,})\ \|\ [NRSU]{1,2}\ \|\ .\ \|\ .+\ \|\ (.*)\ \|$ ]]; then
                  json="$json\"${BASH_REMATCH[1]}\":[\"${BASH_REMATCH[2]//, /\",\"}\"],"
              fi
          done < $WIKI_PATH
          json=${json/%?/}}
          echo $json | jq "." > $ABBS_JSON

      - name: Generate commit message
        working-directory: .wiki
        run: |
          echo "[actions] Update abbreviations json" > $COMMIT_MESSAGE
          echo "" >> $COMMIT_MESSAGE
          echo "" >> $COMMIT_MESSAGE
          git log --after '$(date +"%Y-%m-%d +0000" --date "1 day ago")' --pretty='Co-authored-by: %an <%ae>' | uniq >> $COMMIT_MESSAGE
          cat $COMMIT_MESSAGE

      - name: Remove unneeded files
        run: |
          rm -rf .wiki

      - name: Stage and count changes
        id: staging
        run: |
          git add compass/data/abbs.json
          echo "NUM_OF_STAGED=$(git diff --staged --name-only | wc -l)" >> $GITHUB_OUTPUT

      - name: Push to master
        if: steps.staging.outputs.NUM_OF_STAGED > 0
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add compass/data/abbs.json
          git commit -F $COMMIT_MESSAGE
          git push
