name: Generate pot files from compass data

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "compass/compass-data/data/**"


jobs:
  generate_pot_from_data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate pot files
        run: |
          CARD_POT=compass/locale/card.pot
          HERO_POT=compass/locale/hero.pot
          STAGE_POT=compass/locale/stage.pot
          POT_HEADER="# SOME DESCRIPTIVE TITLE.
          # Copyright (C) YEAR ORGANIZATION
          # FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
          #
          msgid \"\"
          msgstr \"\"
          \"Project-Id-Version: PACKAGE VERSION\n\"
          \"POT-Creation-Date: $(date +"%Y-%m-%d %H:%M%z")\n\"
          \"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n\"
          \"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n\"
          \"Language-Team: LANGUAGE <LL@li.org>\n\"
          \"MIME-Version: 1.0\n\"
          \"Content-Type: text/plain; charset=UTF-8\n\"
          \"Content-Transfer-Encoding: 8bit\n\"
          \"Generated-By: pot-data.yml\n\"

          "
          echo "$POT_HEADER" > $CARD_POT
          echo "$POT_HEADER" > $HERO_POT
          echo "$POT_HEADER" > $STAGE_POT
          for path in $(ls compass/compass-data/data/card/*.json); do
              num=$(cat $path | jq -r .num)
              name=$(cat $path | jq -r .name)
              ability=$(cat $path | jq -r .ability)
              echo "#: $num@msgid \"$name\"@msgstr \"\"@@msgid \"$ability\"@msgstr \"\"@" | tr "@" "\n" >> $CARD_POT
          done
          for path in $(ls compass/compass-data/data/hero/*.json); do
              num=$(cat $path | jq -r .num)
              name=$(cat $path | jq -r .name)
              ultname=$(cat $path | jq -r .ultname)
              ultinvincible=$(cat $path | jq -r .ultinvincible)
              ult=$(cat $path | jq -r .ult)
              haname=$(cat $path | jq -r .haname)
              ha=$(cat $path | jq -r .ha)
              abilityname=$(cat $path | jq -r .abilityname)
              ability=$(cat $path | jq -r .ability)
              echo "#: $num@msgid \"$name\"@msgstr \"\"@@msgid \"$ultname\"@msgstr \"\"@@msgid \"$ultinvincible\"@msgstr \"\"@@msgid \"$ult\"@msgstr \"\"@@msgid \"$haname\"@msgstr \"\"@@msgid \"$ha\"@msgstr \"\"@@msgid \"$abilityname\"@msgstr \"\"@@msgid \"$ability\"@msgstr \"\"@" | tr "@" "\n" >> $HERO_POT
          done
          for path in $(ls compass/compass-data/data/stage/*.json); do
              id=$(cat $path | jq -r .id)
              name=$(cat $path | jq -r .name)
              description=$(cat $path | jq -r .description)
              echo "#: $id@msgid \"$name\"@msgstr \"\"@@msgid \"$description\"@msgstr \"\"@" | tr "@" "\n" >> $STAGE_POT
          done

      - name: Push to master
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add compass/locale/*.pot
          git commit -m "[actions] Update pot files"
          git push
